name: "pypi"
on:
  release:
    types: [published]

jobs:
  push_to_pypi:
    name: Publish python package on release
    runs-on: ubuntu-20.04
    steps:
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}